### PR TITLE
fix: edited .gitignore and settings.json

### PR DESCRIPTION
**Pull request by ghost**
1. .gitignore has been modified for files and folders added to build CI within Clean-Code-Team (Team 1).

2. Modified the settings.json file for the visual study code user inside the Clean-Code-Team (Team 1).

### CODE REVIEW

**Review by NiceGuy1313 — APPROVED** [review]
Thank you for fixing the bug

**Comment by doyoon323** [comment]
Everything is done well!

**Comment by doyoon323** [comment]
Everything is done well!

**Review by doyoon323 — APPROVED** [review]
Everything is done well!

**Pull request merged**
