### PR TITLE
docs: CleanCode.md update

### PR DESCRIPTION
**Pull request by ghost**
The implemented features have been added to CleanCode.md.

### CODE REVIEW

**Review by alicek0 — APPROVED** [review]

**Comment by ghost** [comment]
To fix CI-related build failures, unused packages were commented out.

**Review by jeongwoo903 — APPROVED** [review]
Nice document management. So good 👍

**Review by 258xsw — COMMENTED** [review]
I think I need to change my part to the ending scene.

**Review by NiceGuy1313 — APPROVED** [review]
Good!!

**Pull request merged**
